steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/fastapi-app', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/fastapi-app']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'fastapi-service',
        '--image',
        'gcr.io/$PROJECT_ID/fastapi-app',
        '--platform',
        'managed',
        '--region',
        'us-central1',
        '--allow-unauthenticated'
      ]

images:
  - gcr.io/$PROJECT_ID/fastapi-app
